AWSTemplateFormatVersion: '2010-09-09'

Description: RDS Mysql Instance

Parameters:
  DbName:
    Type: String
  DbUser:
    Type: String
  DbPass:
    Type: String
    NoEcho: true

Resources:
  GIRDSMysqlInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DbName
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Ref DbPass
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PubliclyAccessible: True
      AllocatedStorage: "5"
      DBInstanceIdentifier: "GI-RDS-Mysql-Instance1"

