AWSTemplateFormatVersion: '2010-09-09'

Description: RDS Mysql Instance

Resources:
  GIRDSMysqlInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName:  '{{resolve:secretsmanager:GISecret:SecretString:GIDbName}}'
      MasterUsername:  '{{resolve:secretsmanager:GISecret:SecretString:GIDBUser}}'
      MasterUserPassword:  '{{resolve:secretsmanager:GISecret:SecretString:GIDBPass}}'
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PubliclyAccessible: True
      AllocatedStorage: "5"
      DBInstanceIdentifier: "GI-RDS-Mysql-Instance1"

